package io.github.riijen.dotapal_v2.model;

/**
 * Created by Ryan on 15-03-28.
 */
public enum Item {

    BLINKDAGGER ("blink", "1", "Blink Dagger"),
    BLADESOFATTACK ("blades_of_attack", "2", "Blades Of Attack"),
    BROADSWORD ("broadsword", "3", "Broadsword"),
    CHAINMAIL ("chainmail", "4", "Chainmail"),
    CLAYMORE ("claymore", "5", "Claymore"),
    HELMOFIRONWILL ("helm_of_iron_will", "6", "Helm Of Iron Will"),
    JAVELIN ("javelin", "7", "Javelin"),
    MITHRILHAMMER ("mithril_hammer", "8", "Mithril Hammer"),
    PLATEMAIL ("platemail", "9", "Platemail"),
    QUARTERSTAFF ("quarterstaff", "10", "Quarterstaff"),
    QUELLINGBLADE ("quelling_blade", "11", "Quelling Blade"),
    RINGOFPROTECTION ("ring_of_protection", "12", "Ring Of Protection"),
    STOUTSHIELD ("stout_shield", "182", "Stout Shield"),
    GAUNTLETS ("gauntlets", "13", "Gauntlets"),
    SLIPPERS ("slippers", "14", "Slippers"),
    MANTLE ("mantle", "15", "Mantle"),
    BRANCHES ("branches", "16", "Branch"),
    BELTOFSTRENGTH ("belt_of_strength", "17", "Belt Of Strength"),
    BOOTSOFELVES ("boots_of_elves", "18", "Band Of Elvenskin"),
    ROBES ("robe", "19", "Robes of the Magi"),
    CIRCLET ("circlet", "20", "Circlet"),
    OGREAXE ("ogre_axe", "21", "Ogre Axe"),
    BLADEOFALACRITY ("blade_of_alacrity", "22", "Blade of Alacrity"),
    STAFFOFWIZARDRY ("staff_of_wizardry", "23", "Staff of Wizardry"),
    ULTIMATEORB ("ultimate_orb", "24", "Ultimate Orb"),
    GLOVES ("gloves", "25", "Gloves of Haste"),
    LIFESTEAL ("lifesteal", "26", "Morbid Mask"),
    RINGOFREGEN ("ring_of_regen", "27", "Ring of Regeneration"),
    SOBIMASK ("sobi_mask", "28", "Sobi Mask"),
    BOOTS ("boots", "29", "Boots"),
    GEM ("gem", "30", "Gem of True Sight"),
    CLOAK ("cloak", "31", "Cloak"),
    TALISMANOFEVASION ("talisman_of_evasion", "32", "Talisman of Evasion"),
    CHEESE ("cheese", "33", "Cheese"),
    MAGICSTICK ("magic_stick", "34", "Magic Stick"),
    RECIPIEMAGICWAND("recipe_magic_wand", "35", "Recipe: Magic Wand"),
    MAGICWAND ("magic_wand", "36", "Magic Wand"),
    GHOSTSCEPTER ("ghost", "37", "Ghost Scepter"),
    CLARITY ("clarity", "38", "Clarity Potion"),
    FLASK ("flask", "39", "Flask"),
    DUST ("dust", "40", "Dust"),
    BOTTLE ("bottle", "41", "Bottle"),
    OBSERVERWARD ("ward_observer", "42", "Observer Ward"),
    SENTRYWARD ("ward_sentry", "43", "Sentry Ward"),
    TANGO ("tango","44", "Tango"),
    TANGOSINGLE ("tango_single", "241", "Tango"),
    COURIER ("courier", "45", "Courier"),
    TPSCROLL ("tpscroll", "46", "Scroll"),
    BOOTSOFTRAVEL ("recipe_travel_boots", "47", "Recipe: Boots of Travel"),
    TRAVELBOOTS ("travel_boots", "48", "Boots of Travel"),
    RECIPEPHASEBOOTS ("recipe_phase_boots", "49", "Recipe: Phase Boots"),
    PHASEBOOTS ("phase_boots", "50", "Phase Boots"),
    DEMONEDGE ("demon_edge", "51", "Demon Edge"),
    EAGLESONG ("eagle", "52", "Eaglesong"),
    REAVER ("reaver", "53", "Reaver"),
    RELIC ("relic", "54", "Relic"),
    HYPERSTONE ("hyperstone", "55", "Hyperstone"),
    RINGOFHEALTH ("ring_of_health", "56", "Ring of Health"),
    VOIDSTONE ("void_stone", "57", "Void Stone"),
    MYSTICSTAFF ("mystic_staff", "58", "Mystic Staff"),
    ENERGYBOOSTER ("energy_booster", "59", "Energy Booster"),
    POINTBOOSTER ("point_booster", "60", "Point Booster"),
    VITALITYBOOSTER ("vitality_booster", "61", "Vitality Booster"),
    RECIPEPOWERTREADS ("recipe_power_treads", "62", "Recipe Power Treads"),
    POWERTREADS ("power_treads", "63", "Power Treads"),
    HANDOFMIDAS ("hand_of_midas", "65", "Hand of Midas"),
    OBLIVIONSTAFF ("oblivion_staff", "67", "Oblivion Staff"),
    PERSEVERANCE ("pers", "69", "PERSEVERANCE"),
    POORMANSSHIELD ("poor_mans_shield", "71", "Poor Mans Shield"),
    BRACER ("bracer", "73", "Bracer"),
    WRAITHBAND ("wraith_band", "75", "Wraith Band"),
    NULLTALISMAN ("null_talisman", "77", "Null Talisman"),
    MEKANSM ("mekansm", "79", "Mekansm"),
    VLADMIR ("valdmir", "81", "Vladmir"),
    BUCKLER ("buckler", "86", "Buckler"),
    RINGOFBASILIUS("ring_of_basilius", "88", "Ring of Basilius"),
    PIPE ("pipe", "89", "Pipe of Insight"),
    URN ("urn_of_shadows", "92", "Urn of Shadows"),
    HEADDRESS ("headdress", "94", "Headdress"),
    SHEEPSTICK ("sheepstick", "96", "Sheepstick"),
    ORCHID ("orchid", "98", "Orchid"),
    CYCLONE ("cyclone", "99", "Cyclone"),
    FORCESTAFF ("force_staff", "102", "Force Staff"),
    DAGON ("dagon", "104", "Dagon"),
    DAGON2 ("dagon_2", "201", "Dagon"),
    DAGON3 ("dagon_3", "202", "Dagon"),
    DAGON4 ("dagon_4", "203", "Dagon"),
    DAGON5 ("dagon_5", "204", "Dagon"),
    NECRO ("necronomicon", "106", "Necro"),
    NECRO2 ("necronomicon_2", "193", "Necro"),
    NECRO3 ("necronomicon_3", "194", "Necro"),
    ULTIMATESCEPTER ("ultimate_scepter", "108", "Aghs"),
    REFRESHER ("refresher", "110", "Refresher"),
    ASSAULT ("assault", "112", "Assault Curiass"),
    HEART ("heart", "114", "Heart" ),
    BKB ("black_king_bar", "116", "Black King Bar"),
    AEGIS ("aegis", "117", "Aegis"),
    TRANQUILBOOTS	("tranquil_boots", "214", "Tranquil Boots"),
    AQUILA		("ring_of_aquila", "212", "Ring of Aquila"),
    HEAVENSHALBERD	("heavens_halberd", "210", "Heaven's Halberd"),
    ABYSSALBLADE	("abyssal_blade", "208", "Abyssal Blade"),
    RODOFATOS	("rod_of_atos", "206", "Rod of Atos"),
    VEILOFDISCORD	("veil_of_discord", "190", "Veil of Discord"),
    SMOKE		("smoke_of_deceit", "188", "Smoke of Deceit"),
    MEDALLION	("medallion_of_courage", "187", "Medallion of Courage"),
    ORBOFVENOM	("orb_of_venom", "181", "Orb of Venom"),
    ARCANEBOOTS	("arcane_boots", "180", "Arcane Boots"),
    SOULRING	("soul_ring", "178", "Soul Ring"),
    ETHEREALBLADE	("ethereal_blade", "176", "Ethereal Blade"),
    DIFFUSAL2	("diffusal_blade_2", "196", "Diffusal Blade lv. 2"),
    DIFFUSAL	("diffusal_blade", "174", "Diffusal Blade"),
    MASKOFMADNESS	("mask_of_madness", "172", "Mask of Madness"),
    YASHA		("yasha", "170", "Yasha"),
    DESOLATOR	("desolator", "168", "Desolator"),
    MAELSTROM	("maelstrom", "166", "Maelstrom"),
    HELMOFDOM	("helm_of_the_dominator", "164", "Helm of the Dominator"),
    SANGE		("sange", "161", "Sange"),
    SKADI		("skadi", "160", "Eye of Skadi"),
    MJOLLNIR	("mjollnir", "158", "Mjollnir"),
    SATANIC		("satanic", "155", "Satanic"),
    SANGEYASHA	("sange_and_yasha", "154", "Sange and Yasha"),
    SHADOWBLADE	("invis_sword", "152", "Shadow Blade"),
    ARMLET		("armlet", "151", "Armlet of Mordiggian"),
    CRYSTALIS	("lesser_crit", "149", "Crystalis"),
    MANTASTYLE	("manta", "147", "Manta Style"),
    BATTLEFURY	("bfury", "145", "Battlefury"),
    SKULLBASHER	("basher", "143", "Skull Basher"),
    DAEDALUS	("greater_crit", "141", "Daedalus"),
    BUTTERFLY	("butterfly", "139", "Butterfly"),
    RADIANCE	("radiance", "137", "Radiance"),
    MONKEYKING	("monkey_king_bar", "135", "Monkey King Bar"),
    RAPIER		("rapier", "133", "Divine Rapier"),
    HOODOFDEFIANCE	("hood_of_defiance", "131", "Hood of Defiance"),
    SOULBOOSTER	("soul_booster", "129", "Soul Booster"),
    BLADEMAIL	("blade_mail", "127", "Blade Mail"),
    CRIMSONGUARD	("crimson_guard", "242", "Crimson Guard"),
    VANGUARD	("vanguard", "125", "Vanguard");



    private final String name;
    private final String id;
    private final String localizedName;

    Item(String name, String id, String localizedName) {
        this.name = name;
        this.id = id;
        this.localizedName = localizedName;
    }

}
